"""Update User balance field

Revision ID: 432f48346962
Revises: 1f424c21aed2
Create Date: 2024-09-18 06:55:32.730699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '432f48346962'
down_revision = '1f424c21aed2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###
